name = "openflarestack"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = "../new-ui/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "openflarestack-db"
database_id = "fb72de2d-283f-4310-945e-434cfaa33dd6"
migrations_dir = "src/db/migrations"

[[durable_objects.bindings]]
name = "CONVERSATION_ROOM"
class_name = "ConversationRoom"

[[durable_objects.bindings]]
name = "DISCORD_GATEWAY"
class_name = "DiscordGatewayRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ConversationRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["DiscordGatewayRoom"]

[[queues.producers]]
binding = "QUEUE"
queue = "openflarestack-queue"

[[queues.consumers]]
queue = "openflarestack-queue"
max_batch_size = 10
max_batch_timeout = 5

[[send_email]]
name = "EMAIL"

[[r2_buckets]]
binding = "R2"
bucket_name = "openflarestack-attachments"

[[kv_namespaces]]
binding = "KV"
id = "6a8a0b8cbf3d4b62b736798ed77475b0"

[vars]
ENVIRONMENT = "production"
FRONTEND_URL = "https://openflarestack.mrsan.workers.dev"
BETTER_AUTH_URL = "https://openflarestack.mrsan.workers.dev"
